### ISSUE TITLE
Not an issue but enhancement with code

### ISSUE THREAD

**Issue by agponte** [marcferna/CakePHP-GoogleMapHelper#3]
I needed to insure that only one infoWindow was open at a time.  I initialized a variable at the top of the javascript and used to to close just before opening a new one.

~ line 113 just before other variables are declared I added va

~ line 212 I modified the setMarker function to be:

function setMarker(map, id, position, title, icon, shadow, content, showInfoWindow){
    var index = markers.length;
    markersIds[markersIds.length] = id;
    markers[index] = new google.maps.Marker({
        position: position,
        map: map,
        icon: icon,
        shadow: shadow,
        title:title
    });
    if(content != '' && showInfoWindow){
        var infowindow = new google.maps.InfoWindow({
            content: content
        });
        google.maps.event.addListener(markers[index], 'click', function() {
            if (prev) {
                prev.close();
            }
            prev = infowindow;
            infowindow.open(map,markers[index]);
        });
    }
}

**Comment by marcferna** [comment]
Closing this issue since I got no response
