### ISSUE TITLE
now place search box

### ISSUE THREAD

**Issue by BakhtawarGill** [marcferna/CakePHP-GoogleMapHelper#32]
i am using this class and this is working fantastic.
i have written few line of codes for place search box, how can i add this to your git hub project.

**Comment by marcferna** [comment]
You can create a pull request via Github:
https://help.github.com/articles/using-pull-requests/

**Comment by BakhtawarGill** [comment]
i m not a git master, i have already pulled your help and using it, how tu
push my code to get it emerged in your code.

**Comment by marcferna** [comment]
@BakhtawarGill 
1 - Fork the repository
2 - Clone it in your system
3 - Make the changes
4 - Push changes into your branch
5 - Create a pull request

There is plenty of info in the internet on how to do this.
http://stackoverflow.com/questions/14680711/how-to-do-a-github-pull-request

Thanks again!

**Comment by BakhtawarGill** [comment]
thanks to you man...
i will read the stuff and upload as you have said as soon as possible.

Bakhtawar Gill
Software Engineer
Mobile|+923216444484
software.engineer.fcc@gmail.com
