### ISSUE TITLE
AppHelper Not found

### ISSUE THREAD

**Issue by elarion83** [marcferna/CakePHP-GoogleMapHelper#36]
Hi, 

I'm writing here hoping for an quick answer please :x When I Extend Apphelper with GoogleMapHelper, my view show me this error : 

"AppHelper not found", I don't know what to do.. please.. help <3

**Comment by marcferna** [comment]
Can you provide more information? How are you importing the helper?

Also, please check the [example app](https://github.com/marcferna/CakePHP-GoogleMapHelper/tree/master/ExampleApp).

**Comment by elarion83** [comment]
Hi,

I'm using cakephp3. So I created a GoogleMapHelper.php file in my View/Helper folder with the content that I found in the GoogleMapHelper.php on thid Git.

And I created a AppHelper.php file in my View/Helper folder. 

And I add this line in my controller : public $helpers = array('GoogleMap');   //Adding the helper

And the error show up... :/

**Comment by marcferna** [comment]
Thanks for the info. I've never tested the helper with CakePHP 3. I'll try and update the code if necessary

**Comment by marcferna** [comment]
I upgraded the helper to work with CakePHP3 - you can find it in the `CakePHP3` branch here: https://github.com/marcferna/CakePHP-GoogleMapHelper/tree/CakePHP3

Closing this issue, let me know if you have any other problems.
