### ISSUE TITLE
Cakephp v3

### ISSUE THREAD

**Issue by elarion83** [marcferna/CakePHP-GoogleMapHelper#37]
Hi ! Thanks for this script and the version for cakephp3 but I got another issue.

This time the error that's shows up is : 

Error: Unsupported operand types 
File C:\wamp\www\Nico\vendor\cakephp\cakephp\src\View\Helper\HtmlHelper.php 
Line: 517

From where the issue come from ?

I'll pay you a beer if you can help me <3

**Comment by marcferna** [comment]
Remove the `false` last argument from the `HTML->script` calls.

Note that I only updated the helper to CakePHP3, the examles haven't been updated yet

**Comment by elarion83** [comment]
Thanks a lot man ! 

Now the map won't show up but there's some post with the same issue on this git, I'm going to see if any solution can fix my trouble.

Ps : Awesome job !

**Comment by elarion83** [comment]
I'm back !

So, there's no similar issue :/

I just got a blank space when I use : echo $this->GoogleMap->map(); 
with this error in the console : Uncaught ReferenceError: google is not defined(anonymous function) @ 4:81

And I got nothing when I use : $this->GoogleMap->map();

**Comment by marcferna** [comment]
Are importing the necessary javascrip?

**Comment by elarion83** [comment]
Yeah, i'm using <?php $this->Html->script('http://maps.google.com/maps/api/js?sensor=true'); ?>  on my view :/

**Comment by marcferna** [comment]
What about `<?= $this->Html->script('http://maps.google.com/maps/api/js?key=YOUR_API_KEY&sensor=true'); ?>`?

**Comment by marcferna** [comment]
Can you make sure with the browser Developer Tools that the library is loading properly? It looks like is isn't...

**Comment by elarion83** [comment]
In the console, in "script" (with chrome) I got my toolbar.js, debug_kit and Jquery but no Google.

**Comment by marcferna** [comment]
So for some reason the Google library is not being loaded...i think this is an issue on how you load the JS and not with the Helper. Closing this issue
